### PR TITLE
Bundle c-blosc and build from source

### PR DESCRIPTION
**Pull request by mulimoen**
This is an example of how one can bundle `c-blosc` and build from source with `CMake`. This is added by using a separate crate to keep download size and build time down.

* The compression test for SNAPPY is skipped, as this requires SNAPPY to be installed on the target machine.
* This PR works on macos, linux and windows (gnu+msvc).
* The bundled `c-blosc` is v1.20.0, but this can be changed easily.

### CODE REVIEW

**Comment by asomers** [comment]
This adds an awful lot of complication to the crate to solve a problem that ought to be solved by the package manager instead.  Why not just use the package manager?  I know you said that Ubuntu 18.04's repository's version of c-blosc was too old.  But backporting a new c-blosc package would be simpler than building c-blosc as part of blosc-rs.

**Comment by mulimoen** [comment]
I hope to use `blosc` statically in `hdf5` for all applicable platforms. Neither Mac nor windows has an official package manager, and building from source makes cross compilation a lot easier. Distribution of binaries is greatly simplified as no dynamic libraries needs to be included in the bundle (does `blosc` come statically prebuilt?). And the barrier of entry is greatly reduced for experimentation by new developers

**Comment by asomers** [comment]
Then why not build c-blosc as part of the process of packaging hdf5?

**Comment by mulimoen** [comment]
We don't do packaging ourselves, but wish to do this as easy as possible for end-users. I was hoping to upstream the work done in `hdf5-rust` so other users of `blosc` could benefit from this, and make packaging scientific applications very simple, ideally just to copy the resulting binary from your local computer to the cluster/cloud.

**Comment by asomers** [comment]
It looks like you created a separate crate to handle building c-blosc from src.  IMHO that's the best way to do it.  I'm going to close this issue now.
https://github.com/mulimoen/rust-blosc-src

**Pull request closed without merging**
